# Generated by Django 4.2.1 on 2023-05-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
